# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any dependencies
RUN npm install

# Bundle the app source
COPY . .

# Expose the port the app runs in
EXPOSE 4000

# Define the command to run the app
CMD [ "node", "gateway.js" ]
